name: "ESLint test"

on: [pull_request]

jobs:
  eslint:
    name: Run eslint scanning
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm prune

      - name: Run ESLint
        run: npx eslint *.js installer/*.js components/*.js --config eslint.config.js
        continue-on-error: false
